language: python

install:
    - npm install --verbose
    - wget https://github.com/gohugoio/hugo/releases/download/v0.32.2/hugo_0.32.2_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
    - pip install awscli

script:
    - npm run build
    - hugo --config config.toml --destination output
    - aws personal s3 sync --delete --acl public-read public/ s3://tdhopper.com
    - aws configure set preview.cloudfront true
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
    email: false
